In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]

# 데이터로부터 직접 텐서 생성하기
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)

x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data)

# x_data의 속성을 유지해서.. 1만 있는 tensor로
print(f"Ones Tensor : \n{x_ones}\n")

Ones Tensor : 
tensor([[1, 1],
        [1, 1]])



In [5]:
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f"Random Tensor : \n{x_rand}\n")

Random Tensor : 
tensor([[0.7074, 0.3403],
        [0.2352, 0.5049]])



In [6]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8909, 0.7222, 0.5420],
        [0.4473, 0.4949, 0.9923]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
if torch.cuda.is_available():
  print("torch can be used!\n")
  tensor = tensor.to('cuda')

else:
  print('sorry....')

torch can be used!



In [9]:
tensor = torch.ones(4, 4)

print(f"First row : {tensor[0]}")
print(f"Last column : {tensor[... , -1]}")

tensor[: , 1] = 0

print(tensor)

First row : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)

In [11]:
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
n = np.ones(5)
t = torch.from_numpy(n)

In [13]:
np.add(n , 1, out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
